version: '2'

services:
  server:
    build: ./src
    command: bash -c "./run.sh"
    volumes:
      - type: bind
        source: ./src/logs
        target: /var/log/erss
    ports:
      - "12345:12345"
